name: analizaKodu

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Cppcheck
      run: sudo apt-get update && sudo apt-get install -y cppcheck

    - name: Run Cppcheck
      run: cppcheck --enable=all --inconclusive --std=c++17 --quiet Etap2/main.cpp Etap2/client.cpp 2> cppcheck-report.txt


